version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala:
  - 3.0.0-RC3

env:
  - SCALAJS_VERSION=          ADOPTOPENJDK=8
  - SCALAJS_VERSION=1.5.1     ADOPTOPENJDK=8

install:
  - git fetch --tags # get all tags for sbt-dynver

script: ./build.sh
